# Generated by Django 2.1.5 on 2019-03-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fobi', '0015_auto_20180130_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formentry',
            name='success_page_message',
            field=models.TextField(blank=True, help_text='Custom message text to display after a valid survey is submitted', null=True, verbose_name='Success page message'),
        ),
    ]
